---

- name: grafana-install | Ensure Grafana user is exists
  user: name={{ grafana_user }} system=yes

- name: grafana-install | Make Grafana home
  file: path={{grafana_home}} state=directory owner={{grafana_user}} group={{grafana_group}} mode=0755

- name: grafana-install | Download Grafana
  get_url: url=http://grafanarel.s3.amazonaws.com/grafana-{{ grafana_version }}.tar.gz dest={{grafana_home}}/grafana-{{grafana_version}}.tar.gz
  when: not grafana_source

- name: grafana-install | Extract Grafana
  unarchive: src={{grafana_home}}/grafana-{{grafana_version}}.tar.gz dest={{grafana_home}} copy=false creates={{grafana_home}}/grafana-{{grafana_version}}/README.md
  when: not grafana_source

- name: grafana-install | Link Grafana to current version
  file: src={{grafana_home}}/grafana-{{grafana_version}} dest={{grafana_home}}/www state=link
  when: not grafana_source

- name: grafana-install | Check for Grafana is installed
  stat: path={{grafana_home}}/www
  register: grafana_www

- name: grafana-install | Download Grafana from source
  git: repo=https://github.com/grafana/grafana.git dest={{grafana_home}}/www
  when: grafana_source and not grafana_www.stat.exists
