---

- name: grafana-install | Ensure Grafana user is exists
  user: name={{ grafana_user }}

- name: grafana-install | Make Grafana home
  file: path={{grafana_home}} state=directory owner={{grafana_user}} group={{grafana_group}} mode=0755

- name: grafana-install | Download Grafana
  get_url: url=http://grafanarel.s3.amazonaws.com/grafana-{{ grafana_version }}.tar.gz dest={{grafana_home}}/grafana-{{grafana_version}}.tar.gz

- name: grafana-install | Extract Grafana
  unarchive: src={{grafana_home}}/grafana-{{grafana_version}}.tar.gz dest={{grafana_home}} copy=false creates={{grafana_home}}/grafana-{{grafana_version}}/README.md

- name: grafana-install | Link Grafana to current version
  file: src={{grafana_home}}/grafana-{{grafana_version}} dest={{grafana_home}}/www state=link
